defmodule Castle.PeerProviderStub do
  @moduledoc false

  # A `Config.Provider` that says where it ran and can refuse to run, so that
  # the peer `Castle.Peer` starts can be observed from outside it.
  #
  # It lives here rather than being generated by a test because `test/support`
  # is compiled into castle's own `ebin`, which is on the peer's code path -
  # castle is one of the applications preboot starts. Its state says what to do:
  #
  #   * `marker:` a path, to write the operating system pid of the VM it is
  #     running in there, which is how a test tells whether that VM is still
  #     alive afterwards, and
  #   * `raise:` a message, to fail the way a provider that cannot find what it
  #     needs fails.

  @behaviour Config.Provider

  @impl Config.Provider
  def init(opts) when is_list(opts), do: opts

  @impl Config.Provider
  def load(config, opts) do
    if marker = opts[:marker] do
      File.write!(marker, System.pid())
    end

    if message = opts[:raise] do
      raise message
    end

    Config.Reader.merge(config, Keyword.get(opts, :merge, []))
  end
end
