defmodule Castle.PeerProviderStub do
  @moduledoc false

  # A `Config.Provider` that says where it ran and can refuse to run, so that
  # the peer `Castle.Peer` starts can be observed from outside it.
  #
  # It lives here rather than being generated by a test because `test/support`
  # is compiled into castle's own `ebin`, which is on the peer's code path -
  # castle is one of the applications preboot starts. Its state says what to do:
  #
  #   * `marker:` a path, to write the operating system pid of the VM it is
  #     running in there, which is how a test tells whether that VM is still
  #     alive afterwards,
  #   * `raw:` a string, to write it outside the io system altogether - once
  #     through `:erlang.display_string/1` and once straight to a file
  #     descriptor, which is the door native code would use and the one no relay
  #     can cover,
  #   * `sleep:` a number of milliseconds or `:infinity`, to take longer than it
  #     is allowed to,
  #   * `mode_of:` a glob and `mode_to:` a path, to record the permissions of the
  #     one file the glob matches,
  #   * `snapshot_of:` a glob and `snapshot_to:` a path, to record every path the
  #     glob matches - with its type and permissions - as a consultable term, and
  #   * `raise:` a message, to fail the way a provider that cannot find what it
  #     needs fails.

  @behaviour Config.Provider

  @impl Config.Provider
  def init(opts) when is_list(opts), do: opts

  @impl Config.Provider
  def load(config, opts) do
    if marker = opts[:marker] do
      File.write!(marker, System.pid())
    end

    if raw = opts[:raw] do
      write_outside_the_io_system(raw)
    end

    if glob = opts[:mode_of] do
      record_mode(glob, opts[:mode_to])
    end

    if snapshot = opts[:snapshot_of] do
      record_snapshot(snapshot, opts[:snapshot_to])
    end

    if wait = opts[:sleep] do
      Process.sleep(wait)
    end

    if message = opts[:raise] do
      raise message
    end

    Config.Reader.merge(config, Keyword.get(opts, :merge, []))
  end

  # The permissions of the one file the glob matches, written where the test can
  # read them. Taken from inside the peer, while the pipeline is running, which
  # is the only place the file the configuration is being resolved into can be
  # seen at all: it is renamed away before materialisation returns.
  defp record_mode(glob, to) do
    [path] = Path.wildcard(glob)
    File.write!(to, Integer.to_string(Bitwise.band(File.stat!(path).mode, 0o777), 8))
  end

  # What is there while the pipeline is running, written where the test can read
  # it: one `{path, type, permissions}` triple per match, as a term
  # `:file.consult/1` will read back. Taken from inside the peer for the same
  # reason the mode above is - it is the only moment at which the files being
  # written exist at all.
  defp record_snapshot(glob, to) do
    entries =
      for path <- Enum.sort(Path.wildcard(glob)) do
        stat = File.stat!(path)
        {to_charlist(path), stat.type, Bitwise.band(stat.mode, 0o777)}
      end

    File.write!(to, :io_lib.format(~c"~tp.~n", [entries]))
  end

  defp write_outside_the_io_system(text) do
    :erlang.display_string(String.to_charlist(text))

    # Straight at the descriptor, with no process and no io protocol between.
    port = :erlang.open_port({:fd, 0, 2}, [:out])
    true = Port.command(port, text)
    Port.close(port)
  end
end
