defmodule Castle.SyntheticRelease do
  @moduledoc false

  # Lays out a directory tree shaped like an assembled release, so that the peer
  # `Castle.Peer` starts can be booted for real without a `mix release` and
  # without Forecastle.
  #
  # What matters to `Castle.Peer` is exactly what is built here:
  #
  #   * `erts-<vsn>/bin/erl`, a launcher for the emulator running the tests,
  #     since that is the executable the peer is started with,
  #   * `lib/<app>-<vsn>`, symlinked to each application's real directory, since
  #     that is what `-boot_var RELEASE_LIB` resolves against,
  #   * `releases/<vsn>/preboot.boot`, a `systools` boot script over those
  #     applications - kernel, stdlib, sasl, compiler, elixir and castle
  #     started, anything else on the code path only, which is the shape
  #     Forecastle's preboot script has,
  #   * `releases/<vsn>/<name>.rel`, which is where the emulator version comes
  #     from, and
  #   * `releases/<vsn>/sys.config`.
  #
  # The boot script is generated by `systools` from the real application
  # directories, so the peer boots on the same kind of script a release ships
  # rather than on something hand-written to be easy on it.

  @started [:kernel, :stdlib, :sasl, :compiler, :elixir, :castle]

  @doc """
  Builds a release under `root` and returns its version directory.

  Options:

    * `:vsn` - the release version, and so the name of the version directory
    * `:config` - the term written to `sys.config`
    * `:header` - the comment lines written above it
    * `:apps` - `{app, vsn, dir}` triples to add to the code path without
      starting them, which is how a provider module that lives outside the
      applications preboot starts is reached
  """
  def build(root, opts \\ []) do
    vsn = Keyword.get(opts, :vsn, "1.0.0")
    extra = Keyword.get(opts, :apps, [])
    lib = Path.join(root, "lib")
    vsn_dir = Path.join([root, "releases", vsn])
    File.mkdir_p!(vsn_dir)

    write_emulator(root)
    apps = for app <- @started, do: {app, to_string(Application.spec(app, :vsn)), :permanent}
    apps = apps ++ for {app, app_vsn, dir} <- extra, do: {app, app_vsn, :none, dir}

    make_boot_script(vsn_dir, vsn, apps, link_apps(lib, apps, extra))
    write_rel(Path.join(vsn_dir, "synthetic.rel"), vsn, apps)
    write_sys_config(vsn_dir, opts)

    vsn_dir
  end

  @doc """
  Writes an application holding one module, compiled from `source`, and returns
  the `{app, vsn, dir}` triple that `build/2` takes together with the compiled
  binary, so that a test can load a *different* version of the same module into
  the node running the test.
  """
  def provider_app(dir, app, vsn, module, source) do
    ebin = Path.join(dir, "ebin")
    File.mkdir_p!(ebin)

    [{^module, binary}] = compile(source)
    File.write!(Path.join(ebin, "#{module}.beam"), binary)
    write_app(ebin, app, vsn, [module])

    {{app, vsn, dir}, binary}
  end

  @doc """
  Writes an application with no modules at all, and returns the triple
  `build/2` takes.

  Enough to be loadable, which is what the compile-environment check needs of an
  application before it will read its environment.
  """
  def plain_app(dir, app, vsn) do
    ebin = Path.join(dir, "ebin")
    File.mkdir_p!(ebin)
    write_app(ebin, app, vsn, [])
    {app, vsn, dir}
  end

  defp write_app(ebin, app, vsn, modules) do
    File.write!(
      Path.join(ebin, "#{app}.app"),
      :io_lib.format(~c"~tp.~n", [
        {:application, app,
         [
           {:description, to_charlist(app)},
           {:vsn, to_charlist(vsn)},
           {:modules, modules},
           {:registered, []},
           {:applications, [:kernel, :stdlib, :elixir]}
         ]}
      ])
    )
  end

  # Two versions of one module are compiled in the same node here, which is a
  # redefinition as far as the compiler is concerned. Only the binaries are
  # wanted; which of them the node is left holding is settled by the test.
  defp compile(source) do
    previous = Code.compiler_options(ignore_module_conflict: true)

    try do
      Code.compile_string(source)
    after
      Code.compiler_options(previous)
    end
  end

  # The launcher a release carries is not the one an OTP installation carries: a
  # release's is rewritten to find its root from its own location, since the
  # release is somewhere else. This is the same idea, written out rather than
  # symlinked, so that the emulator is found wherever the test tree happens to
  # be and whatever the installation's own launcher would have made of it.
  defp write_emulator(root) do
    erts = "erts-#{:erlang.system_info(:version)}"
    bin = Path.join([root, erts, "bin"])
    File.mkdir_p!(bin)
    erl = Path.join(bin, "erl")

    File.write!(erl, """
    #!/bin/sh
    ROOTDIR="#{:code.root_dir()}"
    BINDIR="$ROOTDIR/#{erts}/bin"
    EMU=beam
    PROGNAME=erl
    export EMU ROOTDIR BINDIR PROGNAME
    exec "$BINDIR/erlexec" ${1+"$@"}
    """)

    File.chmod!(erl, 0o755)
  end

  defp link_apps(lib, apps, extra) do
    File.mkdir_p!(lib)
    sources = Map.new(extra, fn {app, _vsn, dir} -> {app, dir} end)

    for app_spec <- apps do
      {app, vsn} = {elem(app_spec, 0), elem(app_spec, 1)}
      link = Path.join(lib, "#{app}-#{vsn}")
      File.ln_s!(Map.get_lazy(sources, app, fn -> :code.lib_dir(app) end), link)
      to_charlist(Path.join(link, "ebin"))
    end
  end

  # `systools` writes the `.rel` it was given back out beside the boot script,
  # and a version directory holds exactly one release file, so preboot's goes as
  # soon as it has been used - which is what Mix does with its own.
  defp make_boot_script(vsn_dir, vsn, apps, paths) do
    path = Path.join(vsn_dir, "preboot")
    write_rel(path <> ".rel", vsn, apps)
    lib = Path.expand(Path.join(vsn_dir, "../../lib"))

    {:ok, :systools_make, []} =
      :systools.make_script(to_charlist(path), [
        :silent,
        :no_dot_erlang,
        :no_warn_sasl,
        {:path, paths},
        {:variables, [{~c"RELEASE_LIB", to_charlist(lib)}]}
      ])

    File.rm!(path <> ".rel")
  end

  defp write_rel(path, vsn, apps) do
    entries =
      for app_spec <- apps do
        {elem(app_spec, 0), to_charlist(elem(app_spec, 1)), elem(app_spec, 2)}
      end

    rel =
      {:release, {~c"synthetic", to_charlist(vsn)}, {:erts, :erlang.system_info(:version)},
       entries}

    File.write!(path, :io_lib.format(~c"~tp.~n", [rel]))
  end

  defp write_sys_config(vsn_dir, opts) do
    config = Keyword.get(opts, :config, [])
    header = Keyword.get(opts, :header, "%% coding: utf-8\n%% RUNTIME_CONFIG=false\n")

    File.write!(
      Path.join(vsn_dir, "sys.config"),
      [header, :io_lib.format(~c"~tp.~n", [config])]
    )
  end
end
