defmodule Castle do
  @moduledoc """
  Documentation for `Castle`.
  """

  alias Castle.Commands
  alias Castle.Deployment
  alias Castle.Peer

  # The steps a release is given when it asks for none. Mix's own default is
  # [:assemble] and not carrying that over is the one decision customize/1
  # makes on a project's behalf - see its @doc for why, and for what it does
  # instead with a list the project wrote itself.
  @default_steps [:assemble, :tar]

  @doc """
  Makes a Mix release Castle-capable.

  Takes the options `mix release` accepts and returns options `mix release`
  accepts, with the build-time steps Castle needs installed around `:assemble`.
  It is the whole of the integration: a project that calls it names nothing
  else, and what the build does can change between Castle versions without a
  project's release definition changing with it.

      # mix.exs
      defp releases do
        [
          my_app: fn ->
            [
              include_executables_for: [:unix],
              steps: [:assemble, :tar]
            ]
            |> Castle.customize()
          end
        ]
      end

  ## Define the release lazily

  The `fn -> ... end` is not a matter of style, and a release written as a plain
  list will not build. Mix evaluates the project's configuration - all of
  `mix.exs` - every time it loads the project, and that includes the
  `mix deps.get` and `mix deps.compile` runs that have yet to build `castle`
  itself, so a call written outside a function is a call to a module that is not
  there yet. Mix calls the function only once it has been asked for a release,
  by which point every dependency has been compiled.

  ## Steps

  Whatever `:steps` already holds is kept, in the order it was given: the Castle
  steps are spliced around `:assemble`, and nothing else moves. A list with no
  `:assemble` in it - or a `:steps` that is not a list at all - comes back
  untouched, for `mix release` to refuse as it would any other: it validates the
  option itself, and requires exactly one `:assemble`.

  A release that asks for no `:steps` at all gets
  `#{inspect(@default_steps)}`, which is Mix's default plus `:tar`. The
  difference is deliberate. `:tar` is
  what packs `<name>-<vsn>.tar.gz`, and that tarball is what gets copied into a
  deployment's `releases` directory for `bin/castle unpack <vsn>` to read, so a
  version built without one can be assembled and run but can never be installed
  onto a running system - which is the only reason to be using Castle.

  A `:steps` list that *is* given and has no `:tar` in it is honoured as it
  stands, with a warning. Honoured, because it is the project's own list and
  rewriting it would be Castle deciding what a build produces; warned about,
  because the cost is otherwise invisible until an operator is on a deployment
  with nothing to unpack. Add `:tar` after `:assemble` to silence it.

  The warning says what is missing rather than concluding that the release is
  broken, and for two reasons: the deployment an upgrade is installed *onto*
  needs no tarball of its own, so a version that is only ever upgraded from is
  fine without one; and `:tar` is Mix's own way of packing one rather than the
  only way, so a function step in the list may be packing a tarball itself.

  ## What it does not cover

  Castle needs four more things from a project, and none of them is a release
  option this can set:

    * An appup for every application whose code an upgrade replaces: the
      `:appup` project key naming the file, and the compiler that installs it -
      `compilers: Mix.compilers() ++ [:appup]`. See `Mix.Tasks.Compile.Appup`.

    * A relup, generated by `mix forecastle.relup` between two assembled
      releases and left in the project root, which is where post-assembly looks
      for one to pack. See `Mix.Tasks.Forecastle.Relup`.

    * `include_executables_for: [:unix]`. `bin/castle` is a POSIX shell script,
      so nothing on a Windows deployment can drive an upgrade; assembly warns
      about the `.bat` launcher rather than refusing to write it.

    * `rel/env.sh.eex`, if the project wants one of its own. It is optional:
      Mix writes an `env.sh` either way, and the launcher fragment Castle needs
      is appended to whichever one Mix wrote.
  """
  @spec customize(keyword()) :: keyword()
  def customize(opts) when is_list(opts) do
    Keyword.update(opts, :steps, Forecastle.steps(@default_steps), &spliced/1)
  end

  # `Forecastle.steps/1` does the splice and there is deliberately no second
  # implementation of it here: it finds `:assemble`, puts the pre-assembly step
  # before it and the post-assembly step after it, and leaves everything around
  # them where it was. That it is Forecastle's function is the one thing
  # customize/1 exists to keep out of a consumer's `mix.exs`.
  defp spliced(steps) when is_list(steps) do
    warn_missing_tar(steps)
    Forecastle.steps(steps)
  end

  # Not a list, so there is nothing to splice into. `mix release` validates
  # `:steps` and its refusal names the option; a FunctionClauseError raised out
  # of Forecastle would name a module the project never mentioned, which is the
  # one thing this function is for.
  defp spliced(steps), do: steps

  # Said at the build, where the remedy is one atom, because the alternative is
  # an operator meeting it on a deployment as a `bin/castle unpack` with nothing
  # to unpack - and that failure names a missing file rather than the release
  # option that did not ask for it.
  #
  # It states the omission and stops. Nothing here knows the release was meant
  # to be distributed: the system an upgrade is installed *onto* needs no
  # tarball of its own, and `:tar` is Mix's own way of packing one - its
  # `make_tar/1` is private to `Mix.Tasks.Release` - rather than the only way,
  # so a function step in the list may be packing one itself.
  #
  # Nothing is said about a list with no `:assemble`. `Mix.Release`'s own
  # `validate_steps!/1` requires exactly one and names the option when it
  # refuses, and `Forecastle.steps/1` hands such a list back untouched for that
  # refusal to happen. A second implementation of Mix's rule could only drift
  # from it.
  # **The warning states the condition it observed and a conditional
  # consequence, and asserts no verdict.** What this can see is one atom's
  # absence from the list as given. What it cannot see is whether an archive
  # appears anyway: a function step later in the list can pack one itself, or
  # add `:tar` to the steps still to run, and `%Mix.Release{}` carries those
  # remaining steps precisely so a step can. An earlier version of this said the
  # release "is never packed" and that "nothing can install this version" - then
  # acknowledged the counterexample in a trailing sentence without retracting
  # either claim, which is the worst of both: a definite diagnosis on the error
  # channel sending an operator to investigate a packaging failure that may not
  # exist. Say what was seen, say what follows *unless* something else packs it,
  # and stop.
  defp warn_missing_tar(steps) do
    if :assemble in steps and :tar not in steps do
      Mix.shell().error(
        "warning: Castle.customize/1 was given a :steps list with no :tar step. " <>
          "Unless a step of your own packs one, this release will not produce the " <>
          "<name>-<vsn>.tar.gz that is copied into a deployment's releases " <>
          "directory for bin/castle unpack to read - and bin/castle unpack is how " <>
          "a version is installed onto a running system. Add :tar after :assemble " <>
          "if this version is meant to be installed anywhere. A deployment that is " <>
          "only ever upgraded *from* needs no tarball of its own."
      )
    end
  end

  # Every function in this module but customize/1 is a command entry point:
  # `bin/castle` sends each one to the running node over `bin/<release> rpc`,
  # and the launcher's env.sh fragment evaluates make_releases/0 in the preboot
  # VM, on the first start of a deployment. There is no separate CLI layer to
  # carry the process status, so these functions are the command boundary, and
  # it is here that a failure raises.
  #
  # customize/1 is the exception and is not one of them: it runs at build time,
  # in a consumer's `mix.exs`, and returns a value rather than reporting an
  # outcome. It is here rather than in a module of its own because it is the
  # public integration point - a project should have to name `Castle` and
  # nothing else.
  #
  # Raising, rather than halting or returning: the rpc expression runs on the
  # running release node, so halting there would halt the system under
  # management rather than the caller. `Kernel.CLI.rpc_eval/1` catches on the
  # node and the local VM re-raises, printing the reason and exiting non-zero
  # while the running node is left untouched. A returned error value would be
  # discarded - `Kernel.CLI` only inspects the result of a command for `:ok`.
  #
  # `Castle.Commands` holds the operations themselves, returning their outcome
  # rather than acting on the process, so that they can be tested.

  def make_releases do
    report!(Commands.make_releases(rel_dir()))
  end

  # A question, and not a gate anything has to ask: `unpack/1` and `install/1`
  # make the same check themselves, inside the operation, where nothing can
  # happen between the answer and the act. This is how an operator asks without
  # acting - the state it reports is invisible otherwise, because the file can be
  # there while the record the node works from was synthesised. Do not put it
  # back in front of them: a check in a call of its own is a check about a moment
  # that has passed, and `bin/castle` sends each of these as a separate rpc.
  def upgradable do
    report!(Commands.upgradable())
  end

  def unpack(name) when is_binary(name) do
    report!(Commands.unpack(name))
  end

  # Materialising is *inside* `Commands.install/5`, and this composing it here is
  # the bug that put it there. Materialisation ends in a rename onto the target's
  # `sys.config` - a replace by design, and it has to be, because that is the file
  # `:release_handler` reads - so it is not the harmless idempotent work the note
  # below used to call it. Two callers here both materialised before either
  # entered the serialised region, and the loser's providers - evaluated in a
  # second VM, with whatever environment that call had - overwrote the
  # configuration the winner's provisional release was about to boot, after which
  # the loser was refused for the winner's marker. The refused install decided the
  # configuration of the one that succeeded.
  #
  # So there is nothing to compose: `Castle.install/1` is one call, and "an
  # install is serialised" is now true of *this* function rather than of a part of
  # it. See `Castle.Commands.install/5` and `serialised/2`.
  #
  # **And that claim is tested here rather than one layer down, which is what the
  # four defaulted arguments are for.** `Castle.Commands.install/5` already took
  # the handler, the peer and the deployment so that its own suite could drive two
  # concurrent callers through it; but a test that drives *it* cannot see anything
  # composed in *this* function, so the composition that was the whole defect would
  # have been reintroducible with every test still green. `rel_dir` joins them for
  # the same reason it is an argument there - a suite needs a releases directory of
  # its own to contend over, or the cases cannot run async - and the three module
  # arguments follow it because a caller held at `which_releases/0` is the only
  # seam the interleaving has.
  #
  # They are defaults rather than a separate entry point so that `bin/castle`
  # keeps calling `Castle.install/1` over `rpc` and nothing about the deployment
  # is chosen by a caller: see `rel_dir/0`.
  def install(
        vsn,
        rel_dir \\ rel_dir(),
        handler \\ :release_handler,
        peer \\ Peer,
        deployment \\ Deployment
      )
      when is_binary(vsn) do
    report!(Commands.install(vsn, rel_dir, handler, peer, deployment))
  end

  def running(vsn) when is_binary(vsn) do
    report!(Commands.running(vsn))
  end

  def commit(vsn) when is_binary(vsn) do
    report!(Commands.commit(vsn, rel_dir()))
  end

  def remove(vsn) when is_binary(vsn) do
    report!(Commands.remove(vsn))
  end

  def releases do
    report!(Commands.releases())
  end

  # **Nothing here composes materialisation any more, and neither entry point may
  # start again.** It is a *replace*: the last thing it does is rename the
  # resolved configuration onto `sys.config`. In front of an operation it is two
  # steps another caller can get between, which is why `Commands.install/5` took
  # it back inside its own lock — and `commit/1` has now followed, into
  # `Commands.commit/5`.
  #
  # `commit` was left out on the argument that it is different in kind: it makes
  # permanent a version this node already installed and is running, so there is no
  # marker, no reboot and no window between a configuration and a boot of it. The
  # part that was wrong is what the argument then concluded — that putting commit
  # behind the install lock would be "a deadlock dressed as caution, since an
  # install waiting on a reboot is exactly when a commit is wanted". **An install
  # never holds the lock while waiting on a reboot.** `install_release/1` replies
  # before `init:reboot()` and the reboot runs in `release_handler`'s process, so
  # `Commands.install/5` returns and its `trans` releases before the node goes
  # down; `bin/castle install` then polls `Castle.running/1` over separate rpcs
  # that take no lock, and after a restart transition the VM that held it is gone
  # entirely. The only thing a commit can now wait for is a hot install still
  # inside `install_release/1` — and waiting there is right, because committing
  # part-way through an upgrade is what should not happen.
  #
  # What the composition actually left open was the reachable case: a duplicate
  # install of the version being committed, materialising between the two calls.
  # The commit succeeds, that install then fails as already installed, and its
  # configuration is what the newly permanent release boots on the next restart —
  # a failed caller deciding what a successful one boots, which is the failure
  # this protocol exists to prevent, reachable through the one operation left
  # outside it.

  # The release directory. Derived, never chosen by the caller: which file the
  # configuration lands in, and which file the release records go in, are
  # properties of the installation rather than arguments, and a caller's working
  # directory cannot make them name different ones.
  #
  # `Castle.Deployment.root_dir/0` says what that root does and does not decide,
  # and is the one place that says it. The part that bears on these two: it is
  # the right derivation for a release Mix built, and only because Mix sets
  # neither of the two things that would move the release records elsewhere -
  # see castle#23.
  #
  # It is read through `Castle.Deployment` so that there is one place naming it,
  # the same place `Castle.Commands.ensure_own_erts/2` compares it against
  # `RELEASE_ROOT` - which is the one deployment where this derivation names the
  # wrong tree, and where every operation that would act on it refuses.
  defp rel_dir, do: Path.join(Deployment.root_dir(), "releases")

  defp report!({:ok, lines}), do: Enum.each(lines, &IO.puts/1)
  defp report!({:error, message}), do: raise(Castle.Error, message)
end
